version: '3.8'

services:
  estime-frontend:
    image: estime-frontend:release-candidate
    ports:
      - 3000:8888
    environment:
      PE_CONNECT_CLIENT_ID: "{{ PE_CONNECT_CLIENT_ID }}"
      PE_CONNECT_REDIRECT_URI: "{{ PE_CONNECT_REDIRECT_URI }}"
      PE_CONNECT_SCOPE: "{{ PE_CONNECT_SCOPE }}"
      PE_CONNECT_IDENTITY_SERVER_URL: "{{ PE_CONNECT_IDENTITY_SERVER_URL }}"
      TAG_COMMANDER_SCRIPT_URL: "{{ TAG_COMMANDER_SCRIPT_URL_PROD }}"
      TZ: "Europe/Paris"


