version: '3.8'

services:
  estime-frontend:
    image: registry.beta.pole-emploi.fr/estime/estime-frontend
    networks:
     - estime-frontend-network
    ports:
      - 80:80
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  estime-frontend-network:
    name: docker-shared-network
