version: '3.7'

services:
  reverse-proxy:
    image: nginx
    networks:
      - reverse-proxy-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  reverse-proxy-network:
    name: docker-shared-network
