export enum CodesAidesEnum {
  AGEPI = 'AGEPI',
  AIDE_MOBILITE = 'AM',
  ALLOCATION_ADULTES_HANDICAPES = 'AAH',
  ALLOCATION_SOLIDARITE_SPECIFIQUE = 'ASS',
  PRIME_ACTIVITE = 'PA',
  PENSION_INVALIDITE = 'PI'
}