export enum CodesAidesEnum {
  AGEPI = 'AGEPI',
  AIDE_MOBILITE = 'AM',
  AIDE_PERSONALISEE_LOGEMENT = 'APL',
  ALLOCATION_ADULTES_HANDICAPES = 'AAH',
  ALLOCATION_LOGEMENT_FAMILIAL = 'ALF',
  ALLOCATION_LOGEMENT_SOCIAL = 'ALS',
  ALLOCATION_SOLIDARITE_SPECIFIQUE = 'ASS',
  ALLOCATION_SOUTIEN_FAMILIAL = 'ASF',
  ALLOCATION_SUPPLEMENTAIRE_INVALIDITE = 'ASI',
  ALLOCATIONS_FAMILIALES = 'AF',
  COMPLEMENT_FAMILIAL = 'CF',
  PRESTATION_ACCUEIL_JEUNE_ENFANT = 'PAJE',
  PRIME_ACTIVITE = 'PA',
  PENSION_INVALIDITE = 'PI',
  PENSIONS_ALIMENTAIRES = 'PAF',
  RSA = 'RSA'
}