export enum LibellesAidesEnum {
  AGEPI = 'Aide à la Garde d\'Enfants pour Parent Isolé',
  AIDE_MOBILITE = 'Aide à la mobilité',
  AIDE_PERSONNALISEE_LOGEMENT = 'Aide Personnalisée au Logement',
  ALLOCATION_ADULTES_HANDICAPES = 'Allocation aux Adultes Handicapés',
  ALLOCATION_LOGEMENT_FAMILIALE = 'Allocation de Logement Familial',
  ALLOCATION_LOGEMENT_SOCIALE = 'Allocation de Logement Social',
  AIDE_RETOUR_EMPLOI = 'Aide au Retour à l\'Emploi',
  ALLOCATION_SOLIDARITE_SPECIFIQUE = 'Allocation de Solidarité Spécifique',
  ALLOCATION_SOUTIEN_FAMILIAL = 'Allocation de Soutien Familial',
  ALLOCATION_SUPPLEMENTAIRE_INVALIDITE = 'Allocation supplémentaire d\'invalidité',
  ALLOCATIONS_FAMILIALES = 'Allocations Familiales',
  COMPLEMENT_FAMILIAL = 'Complément Familial',
  IMMOBILIER = 'Revenus immobiliers',
  MICRO_ENTREPRENEUR = 'Revenus micro-entreprise',
  PRESTATION_ACCUEIL_JEUNE_ENFANT = 'Prestation d\'Accueil du Jeune Enfant',
  PRIME_ACTIVITE = 'Prime d\'Activité',
  PENSION_INVALIDITE = 'Pension d\'invalidité',
  PENSIONS_ALIMENTAIRES = 'Pensions Alimentaires du Foyer',
  RSA = 'Revenu de Solidarité Active',
  SALAIRE = 'Salaire net',
  TRAVAILLEUR_INDEPENDANT = 'Revenus travailleur indépendant'
}