export enum RoutesEnum {
  HOMEPAGE = '/',
  ACCESSIBILITE = 'accessibilite',
  AIDES = 'aides',
  AIDES_DESCRIPTION = 'description-aides',
  AVANT_COMMENCER_SIMULATION = 'avant-de-commencer',
  CHOIX_TYPE_SIMULATION = 'type-de-simulation',
  DOCUMENTS = 'documents',
  CGU = 'conditions-generales-utilisation',
  CONTACT = 'contact',
  CONTRAT_TRAVAIL = 'contrat-de-travail',
  ETAPES_SIMULATION = 'etapes-simulation',
  MA_SITUATION = 'ma-situation',
  MES_PERSONNES_A_CHARGE = 'mes-personnes-a-charge',
  NOT_FOUND = '404',
  RESSOURCES_ACTUELLES = 'ressources-actuelles',
  RESULTAT_SIMULATION = 'resultat-simulation',
  SIGNIN_CALLBACK = 'signin-callback',
  STATS = 'stats'
}
